package project

import (
	"archive/zip"
	"cli-enonic/internal/app/commands/app"
	"cli-enonic/internal/app/commands/common"
	"cli-enonic/internal/app/commands/remote"
	"cli-enonic/internal/app/commands/sandbox"
	"cli-enonic/internal/app/util"
	"fmt"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/pkg/errors"
	"github.com/urfave/cli"
)

// OSGi Bundle-SymbolicName: tokens of [a-zA-Z0-9_-] separated by dots
var osgiSymbolicNameRegex = regexp.MustCompile(`^[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)*$`)

const XP_READY_TIMEOUT = 3 * time.Minute

// staticJarPath mirrors the gradle layout: build/libs/<name>-<version>.jar
func staticJarPath(prjPath, appName string) string {
	return filepath.Join(prjPath, "build", "libs", fmt.Sprintf("%s-%s.jar", appName, common.STATIC_APP_VERSION))
}

// writeStaticJar packs the contents of appDir into the root of a jar with the given manifest as the first entry.
func writeStaticJar(appDir, jarPath string, manifest Manifest) error {
	if err := os.MkdirAll(filepath.Dir(jarPath), 0755); err != nil {
		return err
	}
	file, err := os.Create(jarPath)
	if err != nil {
		return err
	}
	defer file.Close()

	zw := zip.NewWriter(file)

	// manifest must be the first entry of a jar
	mw, err := zw.CreateHeader(&zip.FileHeader{Name: MANIFEST_PATH, Method: zip.Deflate, Modified: time.Now()})
	if err != nil {
		return err
	}
	if err := manifest.Write(mw); err != nil {
		return err
	}

	err = filepath.WalkDir(appDir, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, err := filepath.Rel(appDir, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		// zip entries always use forward slashes
		name := filepath.ToSlash(rel)

		info, err := entry.Info()
		if err != nil {
			return err
		}

		if entry.IsDir() {
			// directory entries let OSGi find resources by folder (Bundle.findEntries) and keep empty folders
			header := &zip.FileHeader{Name: name + "/", Method: zip.Store, Modified: info.ModTime()}
			header.SetMode(info.Mode())
			_, err := zw.CreateHeader(header)
			return err
		}

		if !info.Mode().IsRegular() {
			fmt.Fprintf(os.Stderr, "Skipping '%s': not a regular file\n", path)
			return nil
		}
		if name == MANIFEST_PATH {
			fmt.Fprintf(os.Stderr, "Skipping '%s': manifest is generated by CLI\n", path)
			return nil
		}

		header := &zip.FileHeader{Name: name, Method: zip.Deflate, Modified: info.ModTime()}
		header.SetMode(0644)
		w, err := zw.CreateHeader(header)
		if err != nil {
			return err
		}
		src, err := os.Open(path)
		if err != nil {
			return err
		}
		defer src.Close()
		_, err = io.Copy(w, src)
		return err
	})
	if err != nil {
		return err
	}

	if err := zw.Close(); err != nil {
		return err
	}
	return file.Close()
}

func buildStaticJar(prjPath, appName string, descriptor *common.AppDescriptor) string {
	manifest, err := buildStaticManifest(appName, descriptor)
	util.Fatal(err, "Could not create application manifest: ")

	jarPath := staticJarPath(prjPath, appName)
	fmt.Fprintf(os.Stderr, "Building static application '%s'...\n", appName)

	err = writeStaticJar(common.GetAppDir(prjPath), jarPath, manifest)
	util.Fatal(err, "Could not build application: ")

	fmt.Fprintf(os.Stderr, "Built %s\n", jarPath)
	return jarPath
}

// ensureStaticAppName returns the application name stored in the .enonic project file,
// asking for it (and persisting it) when missing.
func ensureStaticAppName(c *cli.Context, prjPath string, pData *common.ProjectData) string {
	name := pData.Name
	if name == "" {
		if common.IsForceMode(c) {
			fmt.Fprintf(os.Stderr, "Application name is not set. Add 'name = \"%s\"' to the .enonic file or run without --force\n", DEFAULT_NAME)
			os.Exit(1)
		}

		var nameValidator = func(val interface{}) error {
			str := val.(string)
			if !appNameRegex.MatchString(str) {
				return errors.Errorf("Name '%s' is not valid. It must be min 3 characters long and only contain lowercase letters, digits, and periods [a-z0-9.]", val)
			}
			return nil
		}
		name = strings.ToLower(util.PromptString("Application name", "", DEFAULT_NAME, nameValidator))
		pData.Name = name
		common.WriteProjectData(pData, prjPath)
	}

	if !osgiSymbolicNameRegex.MatchString(name) {
		fmt.Fprintf(os.Stderr, "Application name '%s' is not valid. It must consist of [a-zA-Z0-9_-] segments separated by periods, e.g. %s\n", name, DEFAULT_NAME)
		os.Exit(1)
	}
	return name
}

// waitForXpReady polls the management API until the application install endpoint is available.
// GET on app/install answers 405 once the ApplicationResource is registered, 404 before that and
// connection errors before Jetty is up.
func waitForXpReady(c *cli.Context, sandboxName string, timeout time.Duration) {
	req := common.CreateRequest(c, "GET", "app/install", nil)

	common.StartSpinner(fmt.Sprintf("Waiting for sandbox '%s' to become ready", sandboxName))
	deadline := time.Now().Add(timeout)
	lastResponse := "no response"
	for {
		res, err := common.SendRequestRaw(c, req, 1)
		if err == nil {
			res.Body.Close()
			lastResponse = res.Status
			if res.StatusCode == http.StatusMethodNotAllowed {
				common.StopSpinner()
				fmt.Fprintln(os.Stderr, "Done")
				return
			}
		}
		if time.Now().After(deadline) {
			common.StopSpinner()
			fmt.Fprintf(os.Stderr, "\nTimed out waiting for sandbox '%s' to become ready (last response: %s)\n", sandboxName, lastResponse)
			os.Exit(1)
		}
		time.Sleep(time.Second)
	}
}

// ensureStaticProjectData resolves project data for a Static application. Unlike gradle projects a sandbox
// is optional: it is used only when explicitly requested or already linked to the project; otherwise the
// application is deployed to the active remote (e.g. an XP instance not managed by CLI).
func ensureStaticProjectData(c *cli.Context, sandboxName string) *common.ProjectData {
	ensureValidProjectFolder(".")
	projectData := common.ReadProjectData(".")

	if sandboxName != "" || sandbox.Exists(projectData.Sandbox) {
		// regular flow: validates the sandbox, XP version and distro, may create a new sandbox
		projectData, _ = ensureProjectDataExists(c, ".", sandboxName, "A sandbox is required to deploy the project, "+
			"do you want to create one")
		return projectData
	}

	if projectData.Sandbox != "" {
		fmt.Fprintf(os.Stderr, "Sandbox '%s' linked to the project does not exist.\n", projectData.Sandbox)
	}
	return projectData
}

// installStatic builds a Static application jar and installs it to the active remote (like `project install`).
func installStatic(c *cli.Context) {
	ensureValidProjectFolder(".")
	projectData := common.ReadProjectData(".")

	descriptor, err := common.ReadAppDescriptor(".")
	util.Fatal(err, "Could not read application descriptor: ")

	name := ensureStaticAppName(c, ".", projectData)
	jarPath := buildStaticJar(".", name, descriptor)
	app.InstallFromFile(c, jarPath)
}

// deployStatic builds a Static application jar and installs it into the project sandbox over HTTP.
func deployStatic(c *cli.Context, sandboxName string) error {
	projectData := ensureStaticProjectData(c, sandboxName)
	if projectData == nil {
		return nil
	}

	if c.Bool("continuous") {
		fmt.Fprintln(os.Stderr, "Continuous mode is not supported for Static applications, deploying once...")
	}

	descriptor, err := common.ReadAppDescriptor(".")
	util.Fatal(err, "Could not read application descriptor: ")

	name := ensureStaticAppName(c, ".", projectData)
	jarPath := buildStaticJar(".", name, descriptor)
	fmt.Fprintln(os.Stderr, "")

	sandboxExists := sandbox.Exists(projectData.Sandbox)
	if sandboxExists && !c.Bool("skip-start") {
		if !sandbox.AskToStartSandboxDetached(c, projectData.Sandbox) {
			fmt.Fprintf(os.Stderr, "Sandbox '%s' is not running. Start it and run 'enonic project deploy' again, "+
				"or install the application manually:\n  enonic app install --file %s\n", projectData.Sandbox, jarPath)
			return nil
		}
		waitForXpReady(c, projectData.Sandbox, XP_READY_TIMEOUT)
	}

	if sandboxExists {
		fmt.Fprintf(os.Stderr, "Deploying to sandbox '%s'...\n", projectData.Sandbox)
	} else {
		fmt.Fprintf(os.Stderr, "No sandbox linked to the project, deploying to the active remote (%s)...\n", remote.GetActiveRemote().Url.String())
		fmt.Fprintln(os.Stderr, "Run 'enonic project sandbox <name>' to deploy to a sandbox instead.")
	}
	app.InstallFromFile(c, jarPath)

	return nil
}
