== CMS

Content metadata commands. Currently only one command present here:

----
$ enonic cms

CMS commands

USAGE:
   Enonic CLI cms command [command options] [arguments...]

COMMANDS:
     reprocess  Reprocesses content in the repository.

OPTIONS:
   --help, -h  show help
----

=== Reprocess

Reprocesses content in the repository and *regenerates metadata for the media attachments*. Only content of a media type (super-type = _base:media_) are processed.

Unless the `–skip-children` flag is specified, it processes all descendants of the specified content path.

NOTE: This command should be used after migrating content from Enonic CMS using the cms2xp tool.

 $ enonic cms reprocess [--path <value>] [--skip-children] [-a <value>]

Options:
[cols="1,3", options="header"]
|===
|Option
|Description

|`--path`
|target content path to be reprocessed. Format: `<branch-name>:<content-path>`. e.g `draft:/`

|`--skip-children`
|flag to skip processing of content children

|`--a, --auth`
|authentication token for basic authentication (user:password)
|===

NOTE: if `auth` param is missing CLI will look for `ENONIC_CLI_REMOTE_USER` and `ENONIC_CLI_REMOTE_PASS` environment variables.

_Example:_
====
 $ enonic reprocess -a su:password -s draft:/some-content
====

