== Dumps

List of command for manipulating all repositories can be seen by typing:

----
$ enonic dump

Dump and load complete repositories

USAGE:
   Enonic CLI dump command [command options] [arguments...]

COMMANDS:
     create       Export data from every repository.
     upgrade, up  Upgrade a dump.
     load         Import data from a dump.
     list, ls     List available dumps

OPTIONS:
   --help, -h  show help
----

=== Create

Export data from every repository. The result will be stored in the `$XP_HOME/data/dump` directory.

 $ enonic dump create [-d <value>] [--skip-versions <value>] [--max-version-age <value>] [--max-versions <value>] [-a <value>]

Options:
[cols="1,3", options="header"]
|===
|Option
|Description

|`-d`
|dump name

|`--skip-versions`
|don't dump version-history, only current versions included

|`--max-version-age`
|max age of versions to include, in days, in addition to current version

|`--max-versions`
|max number of versions to dump in addition to current version

|`--archive`
|outputs dump output to an archive (%name%.zip) file (default is false)

|`-a, --auth`
|authentication token for basic authentication (user:password).
|===

NOTE: if `auth` param is missing and there is no valid session CLI will look for `ENONIC_CLI_REMOTE_USER` and `ENONIC_CLI_REMOTE_PASS` environment variables. See <<configuration, configuration section.>>

.Example creating new dump named 'myDump':
----
$ enonic dump create -a su:password -d myDump
----

=== Upgrade

Upgrade a data dump from a previous version to the current version. The output of the upgrade will be placed alongside the dump that is being upgraded and will have the name `<dump-name>_upgraded_<new-version>`.

NOTE: The current version XP installation must be running with the upgraded app deployed.

 $ enonic dump upgrade [-d <value>] [-a <value>]

Options:
[cols="1,3", options="header"]
|===
|Option
|Description

|`-d`
|dump name

|`-a, --auth`
|authentication token for basic authentication (user:password).
|===

NOTE: if `auth` param is missing and there is no valid session CLI will look for `ENONIC_CLI_REMOTE_USER` and `ENONIC_CLI_REMOTE_PASS` environment variables. See <<configuration, configuration section.>>

.Example upgrading dump named 'myDump' to current version:
----
$ enonic dump upgrade -a su:password -d myDump
----

=== List

Lists all the dumps

 $ enonic dump ls

Options:
[cols="1,3", options="header"]
|===
|Option
|Description

|`-a, --auth`
|authentication token for basic authentication (user:password).
|===

NOTE: if `auth` param is missing and there is no valid session CLI will look for `ENONIC_CLI_REMOTE_USER` and `ENONIC_CLI_REMOTE_PASS` environment variables. See <<configuration, configuration section.>>

=== Load

Load data from a named system dump into Enonic XP. The dump read has to be stored in the `$XP_HOME/data/dump` directory. See https://xp.readthedocs.io/en/stable/operations/export.html#operations-export[Export and Import] for more information on system dump/load.

WARNING: A load will delete all existing repositories before loading the repositories present in the system-dump

 $ enonic dump load [--d <value>] [-f] [--upgrade] [--a <value>]

Options:
[cols="1,3", options="header"]
|===
|Option
|Description

|`-d`
|dump name to load

|`-f, --force`
|assume “Yes” as answer to all prompts and run non-interactively

|`--upgrade`
|upgrade the dump if necessary (default is false)

|`--archive`
|loads dump form an archive (%name%.zip) file (default is false)

|`-a, --auth`
|authentication token for basic authentication (user:password)

|===

NOTE: if `auth` param is missing and there is no valid session CLI will look for `ENONIC_CLI_REMOTE_USER` and `ENONIC_CLI_REMOTE_PASS` environment variables. See <<configuration, configuration section.>>

.Example loading dump 'newDump' in a non-interactive mode and upgrade if necessary:
----
$ enonic dump load -a su:password --na newSu:newPassword -d newDump -f --upgrade
----
