== Export

Export and import data from a given repository, branch and content path. To list available commands type:
----
$ enonic export

Export and load repository structures

USAGE:
   Enonic CLI export command [command options] [arguments...]

COMMANDS:
     create  Export data from given repository, branch and content path.
     import  Import data from a named export.

OPTIONS:
   --help, -h  show help
----

=== Create

Extract data from a given repository, branch and content path. The result will be stored in the `$XP_HOME/data/export` directory. This is useful to move a part of a site from one installation to another. See https://xp.readthedocs.io/en/stable/operations/export.html#operations-export[Export and Import] for more information on content export/import.

WARNING: Exporting content will not include the version history of the content, just the current version.

 $ enonic export create [-t <value>] [--path <value>] [--skip-ids] [--skip-versions] [--dry] [-a <value>]

Options:
[cols="1,3", options="header"]
|===
|Option
|Description

|`-t`
|target name to save export

|`--path`
|path of data to export. Format: `<repo-name>:<branch-name>:<node-path>` e.g. `cms-repo:draft:/some-content`

|`--skip-ids`
|Flag to skip ids in data when exporting.

|`--skip-versions`
|Flag to skip versions in data when exporting.

|`--dry`
|Show the result without making actual changes.

|`--a, --auth`
|authentication token for basic authentication (user:password)
|===

NOTE: if `auth` param is missing CLI will look for `ENONIC_CLI_REMOTE_USER` and `ENONIC_CLI_REMOTE_PASS` environment variables.

_Example:_
====
 $ enonic export create -a su:password -t myExport --path cms-repo:draft:/some-content
====

=== Import

Import data from a named export into Enonic XP at the desired content path. The export read has to be stored in the `$XP_HOME/data/export` directory. See https://xp.readthedocs.io/en/stable/operations/export.html#operations-export[Export and Import] for more information on content export/import.

 $ enonic export import [-t <value>] [--path <value>] [--xsl-source <value>] [--xsl-param <value>] [--skip-ids] [--skip-permissions] [--dry] [-a <value>]

Options:
[cols="1,3", options="header"]
|===
|Option
|Description

|`-t`
|a named export to import

|`--path`
|target path for import. Format: `<repo-name>:<branch-name>:<node-path>` e.g. `cms-repo:draft:/some-content`

|`--xsl-source`
|path to xsl file (relative to `<XP_HOME>/data/export`) for applying transformations to node.xml before importing

|`--xsl-param`
|parameters to pass to the XSL transformations before importing nodes. Format: `<parameter-name>=<parameter-value>` e.g. `applicationId=com.enonic.myapp`

|`--skip-ids`
|flag to skip ids when importing

|`--skip-permissions`
|flag to skip permissions when importing

|`--dry`
|show the result without making actual changes.

|`--a, --auth`
|authentication token for basic authentication (user:password)
|===

NOTE: if `auth` param is missing CLI will look for `ENONIC_CLI_REMOTE_USER` and `ENONIC_CLI_REMOTE_PASS` environment variables.

_Example:_
====
 $ enonic export import -a su:password -t myExport --path cms-repo:draft:/some-content
====

[TIP]
====
An XSL file and a set of name=value parameters can be optionally passed for applying transformations to each node.xml file, before importing it.

This option could for example be used for renaming types or fields. The .xsl file must be located in the `$XP_HOME/data/export` directory.
====
