== Export

Extract data from a given repository, branch and content path. The result will be stored in the `$XP_HOME/data/export` directory. This is useful to move a part of a site from one installation to another. See https://xp.readthedocs.io/en/stable/operations/export.html#operations-export[Export and Import] for more information on content export/import.

WARNING: Exporting content will not include the version history of the content, just the current version.

To list available configuration options, type:

----
$ enonic export -h

Export data from a given repository, branch and content path.

USAGE:
   enonic export [command options] [arguments...]

OPTIONS:
   -t value                Target name to save export.
   --path value            Path of data to export. Format: <repo-name>:<branch-name>:<node-path> e.g. 'cms-repo:draft:/'
   --skip-ids              Flag to skip ids in data when exporting.
   --skip-versions         Flag to skip versions in data when exporting.
   --dry                   Show the result without making actual changes.
   --auth value, -a value  Authentication token for basic authentication (user:password)
----

NOTE: if `auth` param is missing and there is no valid session CLI will look for `ENONIC_CLI_REMOTE_USER` and `ENONIC_CLI_REMOTE_PASS` environment variables. See <<configuration, configuration section.>>

.Example exporting data from 'cms-repo' repo, branch 'draft' and path '/some-content' to 'myExport' dump:
----
$ enonic export -a su:password -t myExport --path cms-repo:draft:/some-content
----

== Import

Import data from a named export into Enonic XP at the desired content path. The export has to be stored in the `$XP_HOME/data/export` directory. See https://xp.readthedocs.io/en/stable/operations/export.html#operations-export[Export and Import] for more information on content export/import.

To list available configuration options, type:

----
$ enonic import -h

  Import data from a named export.

  USAGE:
     enonic import [command options] [arguments...]

  OPTIONS:
     -t value                A named export to import.
     --path value            Target path for import. Format: <repo-name>:<branch-name>:<node-path> e.g. 'cms-repo:draft:/'
     --xsl-source value      Path to xsl file (relative to <XP_HOME>/data/export) for applying transformations to node.xml before importing.
     --xsl-param value       Parameters to pass to the XSL transformations before importing nodes. Format: <parameter-name>=<parameter-value> e.g. 'applicationId=com.enonic.myapp'
     --skip-ids              Flag to skips ids when importing
     --skip-permissions      Flag to skips permissions when importing
     --dry                   Show the result without making actual changes.
     --auth value, -a value  Authentication token for basic authentication (user:password)
----

NOTE: if `auth` param is missing and there is no valid session CLI will look for `ENONIC_CLI_REMOTE_USER` and `ENONIC_CLI_REMOTE_PASS` environment variables. See <<configuration, configuration section.>>

.Example:
----
$ enonic import -a su:password -t myExport --path cms-repo:draft:/some-content
----

[TIP]
====
An XSL file and a set of name=value parameters can be optionally passed for applying transformations to each node.xml file, before importing it.

This option could for example be used for renaming types or fields. The .xsl file must be located in the `$XP_HOME/data/export` directory.
====
