include::variables.adoc[]

= Install, upgrade or uninstall Enonic CLI

The CLI is available for Mac, Linux and Windows.
To install the CLI on your local device, visit our https://developer.enonic.com/start[Quickstart page] or follow the instructions below

== Install Enonic CLI

=== NPM

If you have npm installed (on any OS), run the following command in your terminal:

 npm install -g @enonic/cli

=== MacOS

==== Brew

. Enonic CLI is available from the https://brew.sh/[Homebrew package service].
With Homebrew installed, run the following command in your terminal app to add enonic to homebrew known repositories:

 brew tap enonic/cli

. Now you can install CLI by running:

 brew install enonic

==== Direct download

You can download CLI directly from our repository: https://repo.enonic.com/public/com/enonic/cli/enonic/{xp_version}/enonic_{xp_version}_Darwin_64-bit.tar.gz[x64] | https://repo.enonic.com/public/com/enonic/cli/enonic/{xp_version}/enonic_{xp_version}_Darwin_arm64.tar.gz[ARM]

=== Linux

==== wget

Open the Shell and run the following:

 wget -qO- https://repo.enonic.com/public/com/enonic/cli/installer/cli-linux/1.0.0/cli-linux-1.0.0.sh | sh


==== Snapcraft

Open the Shell and run the following:

 $ sudo snap install enonic


==== Direct download

You can download CLI directly from our repository: https://repo.enonic.com/public/com/enonic/cli/enonic/{xp_version}/enonic_{xp_version}_Linux_64-bit.tar.gz[x64] | https://repo.enonic.com/public/com/enonic/cli/enonic/{xp_version}/enonic_{xp_version}_Linux_arm64.tar.gz[ARM] | https://repo.enonic.com/public/com/enonic/cli/enonic/{xp_version}/enonic_{xp_version}_Linux_arm_v6.tar.gz[ARMv6]


=== Windows

==== Scoop

. After having https://scoop.sh/[Scoop command-line installer] installed, open command prompt and add CLI github repo to scoop known repositories with the following command:

 scoop bucket add enonic https://github.com/enonic/cli-scoop.git

. Now you can install CLI by running:

 scoop install enonic


==== Native installer

To install the latest available version on your PC with native installer:

. Download https://repo.enonic.com/public/com/enonic/cli/installer/cli-windows/1.0.0/cli-windows-1.0.0.exe[windows installer].
. Run it and follow the wizard instructions.
. If you need to update the CLI later, just run the installer once again to fetch the latest version.


==== Direct download

You can download CLI directly from our repository: https://repo.enonic.com/public/com/enonic/cli/enonic/{xp_version}/enonic_{xp_version}_Windows_64-bit.zip[x64] | https://repo.enonic.com/public/com/enonic/cli/enonic/{xp_version}/enonic_{xp_version}_Windows_arm_v6.zip[ARMv6]

== Upgrade Enonic CLI

To upgrade to the latest version, run the following command:

 enonic upgrade

IMPORTANT: This command will not work if you installed CLI via direct download or native Windows installer.

You can check if there's a newer version of Enonic CLI by running the following command:

 enonic latest

This will report if there's an upgrade available and what command to run to update CLI.

[subs="attributes"]
----
$ enonic latest

Loading...
You are using the latest version of Enonic CLI: {xp_version}
----


== Uninstall Enonic CLI

Run

 enonic uninstall

to remove Enonic CLI from your system.

IMPORTANT: This command will not work if you installed CLI via direct download or native Windows installer.
