== Installation

The CLI is available for Mac, Linux and Windows. To install the CLI on your local device, visit our https://enonic.com/downloads[downloads page] or follow the instructions below

=== MacOS

. Enonic CLI is available from the https://brew.sh/[Homebrew package service]. With Homebrew installed, run the following command in your terminal app to add enonic to homebrew known repositories:

 brew tap enonic/cli

. Now you can install CLI by running:

 brew install enonic

. If you later want to update the CLI, simply run:

 brew update enonic

=== Linux

If you know exact version you need you can download CLI archive directly from our repository:

 curl -O http://repo.enonic.com/public/com/enonic/cli/enonic/1.0.2/enonic_1.0.2_Linux_64-bit.tar.gz


=== Windows

There are two ways to install CLI on windows

==== Install using Scoop

. After having https://scoop.sh/[Scoop command-line installer] installed, open command prompt and add CLI github repo to scoop known repositories with the following command:

 scoop bucket add enonic https://github.com/enonic/cli-scoop.git

. Now you can install CLI by running:

 scoop install enonic

. Updating CLI is done with the following comand:

 scoop update enonic


==== Windows native installer
To download the latest available CLI and install it on your PC with native installer:

. Download https://enonic.com[windows installer >>>fix link<<<].
. Run it and follow the wizard instructions.
. If you need to update the CLI later, just run the installer once again to fetch the latest version.
