= Release notes

== CLI 3

=== Features

* `sandbox start` starts sandbox in dev mode by default
* `project test` command to execute `gradle test` task for a project
* `sandbox copy` command for copying an existing sandbox
* `threshold` option for the `vacuum` command for specifying age of data to be removed
* `clean` option for the `snapshot restore` command to delete indices before restoring

=== Improvements

* Suggest starting a new sandbox after it's created
* Support short `-s` flag for specifying a sandbox for project commands
* `sandbox upgrade` command will no longer ask which sandbox to upgrade when executed from inside a project's folder
* `project sandbox` command now outputs current project's sandbox


=== Bug fixes

* Removed unsupported options for `upgrade` and `uninstall` commands

== Upgrade notes

* In CLI 3.x, the `sandbox start` command will start the sandbox in dev mode by default. If you want to start the sandbox in prod mode, provide the `--prod` option.
* All the commands that may potentially create a new sandbox (f.ex. `sandbox create` or `project create`) will now suggest starting the new sandbox after it's created. If such a command is used in combination with `-f` (`--force`) option, the sandbox will be started without prompt. This may potentially affect some scripts if the command is followed by another command which now won't be reached because script execution will be taken over by the running sandbox.
