[#sandboxes]
== Sandboxes

Developers may use the CLI to run different instances of XP locally. These instances are called sandboxes.
Each sandbox will be associated with a specific distribution (version) of Enonic XP and will have its own Enonic XP home folder.

The CLI automates setting up, starting, stopping and upgrading sandboxes.
Sandbox commands list is available by running following command:
----
$ enonic sandbox

Manage XP development instances

USAGE:
   Enonic CLI sandbox command [command options] [arguments...]

COMMANDS:
     list, ls         List all sandboxes
     start            Start the sandbox.
     stop             Stop the sandbox started in detached mode.
     create           Create a new sandbox.
     delete, del, rm  Delete a sandbox
     upgrade, up      Upgrades the distribution version.

OPTIONS:
   --help, -h  show help
----

=== Create

Starts a new sandbox wizard asking for a name and an enonic distribution version:

 $ enonic sandbox create [name] [-v <value>]

Options:
[cols="1,3", options="header"]
|===
|Option
|Description

|`name`
|sandbox name

|`-v, --version`
|enonic distribution version
|===

TIP: If all params are present and correct, sandbox is created immediately without wizard.

_Example:_
====
 $ enonic sandbox create myBox mac-sdk-7.0.0-B5
====

=== List

Lists all sandboxes previously created by user:
----
$ enonic sandbox list
----
_Example output:_
----
$ enonic sandbox ls

* Sandbox1 ( windows-sdk-7.0.0-B1 )
  Sandbox2 ( windows-sdk-7.0.0-B1 )
  Sandbox3 ( windows-sdk-7.0.0-B4 )
  Sandbox4 ( windows-sdk-7.0.0-B5 )
----
NOTE: Asterisk marks currently running sandbox

=== Start

Starts a previously created sandbox ensuring that only 1 is started at a time:

 $ enonic sandbox start [name] [-d]

Options:
[cols="1,3", options="header"]
|===
|Option
|Description

|`name`
|sandbox name

|`-d, --detach`
|flag to start sandbox in background
|===

_Example:_
====
 $ enonic sandbox start myBox -d
====

=== Stop

Stops a running sandbox:

 $ enonic sandbox stop

NOTE: only sandboxes started with CLI can be stopped using this command.

_Example:_
====
 $ enonic sandbox stop
====

=== Upgrade

Upgrades enonic distribution used for this sandbox:

 $ enonic sandbox upgrade [name] [-v <value>]

Options:
[cols="1,3", options="header"]
|===
|Option
|Description

|`name`
|sandbox name

|`-v, --version`
|enonic distribution version
|===

NOTE: Downgrades are not permitted.

_Example:_
====
 $ enonic sandbox upgrade myBox -v windows-sdk-7.0.0-B5
====

=== Delete

Deletes a sandbox:

 $ enonic sandbox delete [name]

Options:
[cols="1,3", options="header"]
|===
|Option
|Description

|`name`
|sandbox name
|===
WARNING: All data that may have been created in this sandbox will be deleted.

_Example:_
====
 $ enonic sandbox delete myBox
====
